### ISSUE TITLE
param is missing or the value is empty: active_support/builder

### ISSUE THREAD

**Issue by ThatsNinja** [ruckus/quickbooks-ruby#296] opened 2016-02-21 05:50 UTC
Sorry in advance if I'm missing something obvious here, but I've been at this for quite a few hours.

I'm trying to update a Vendor, and I'm getting back:
```
param is missing or the value is empty: active_support/builder
```

Here's my current controller code (I know, I know. Again, this is many hours in, and I've had the engine out of the car half a dozen times.):
```
  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    @vendor = @vendor_service.fetch_by_id(params[:vendor_id])

    @vendor.id = params[:id]
    @vendor.given_name = params[:given_name]
    @vendor.family_name = params[:family_name]
    @vendor.display_name = params[:display_name]
    @vendor.company_name = params[:company_name]
    @vendor.billing_address = params[:billing_address]
    @vendor.primary_email_address = Quickbooks::Model::EmailAddress.new(params[:primary_email_address][:address])
    @vendor.primary_phone = Quickbooks::Model::TelephoneNumber.new(params[:primary_phone][:free_form_number])

    respond_to do |format|
      if @vendor_service.update(@vendor)
        format.html do
          redirect_to :index, notice: 'Vendor was successfully updated.'
        end
        format.json { render :index, status: :ok }
      else
        format.html { render :edit }
        format.json do
          render json: @vendor.errors, status: :unprocessable_entity
        end
      end
    end
  end
```

... which is failing here:
```
if @vendor_service.update(@vendor)
```

... and here's the object I'm trying to pass above:
```
>> @vendor
=> #<Quickbooks::Model::Vendor id: 62, sync_token: 0, meta_data: {"create_time"=>2016-02-20 14:25:32 -0800, "last_updated_time"=>2016-02-20 14:25:32 -0800}, attachable_ref: nil, title: nil, given_name: , middle_name: nil, family_name: , suffix: nil, company_name: Foo Company, display_name: Another Vendor Foo, print_on_check_name: Foo Company, active?: true, primary_phone: {"free_form_number"=>""}, alternate_phone: nil, mobile_phone: nil, fax_phone: nil, primary_email_address: {"address"=>"email@domain.tld"}, web_site: nil, billing_address: {"line1"=>"", "line2"=>"", "city"=>"", "country_sub_division_code"=>"", "postal_code"=>""}, other_contact_info: nil, tax_identifier: nil, term_ref: nil, balance: 0.0, account_number: nil, is_1099?: false, currency_ref: {"name"=>"United States Dollar", "value"=>"USD", "type"=>nil}>
```

Here's the trace, in relevant part:
```
web_1       | Completed 400 Bad Request in 1376ms (ActiveRestClient: 0.0ms for 0 calls | ActiveRecord: 4.7ms)
web_1       |
web_1       | ActionController::ParameterMissing - param is missing or the value is empty: active_support/builder:
web_1       |   actionpack (4.2.2) lib/action_controller/metal/strong_parameters.rb:249:in `require'
web_1       |   activesupport (4.2.2) lib/active_support/core_ext/hash/conversions.rb:75:in `to_xml'
web_1       |   roxml (3.3.1) lib/roxml/xml/references.rb:301:in `block (2 levels) in update_xml'
web_1       |   roxml (3.3.1) lib/roxml/xml/references.rb:300:in `block in update_xml'
web_1       |   roxml (3.3.1) lib/roxml/xml/references.rb:291:in `update_xml'
web_1       |   roxml (3.3.1) lib/roxml.rb:42:in `block (2 levels) in to_xml'
web_1       |   roxml (3.3.1) lib/roxml.rb:39:in `block in to_xml'
web_1       |   roxml (3.3.1) lib/roxml.rb:35:in `to_xml'
web_1       |   quickbooks-ruby (0.4.2) lib/quickbooks/model/base_model.rb:19:in `to_xml_inject_ns'
web_1       |   quickbooks-ruby (0.4.2) lib/quickbooks/model/base_model.rb:31:in `to_xml_ns'
web_1       |   quickbooks-ruby (0.4.2) lib/quickbooks/service/service_crud.rb:43:in `create'
web_1       |   quickbooks-ruby (0.4.2) lib/quickbooks/service/vendor.rb:8:in `update'
web_1       |   app/controllers/vendors_controller.rb:69:in `block in update'
```

**Comment by ruckus** [comment] 2016-02-22 17:30
Hi @ThatsNinja - sorry to hear you're experiencing issues.

On one hand it looks like the issue is ActiveSupport, but that could be a red herring.

One thing that I'm unsure about: you first fetch the vendor by `params[:vendor_id]` but then when you get that object you assign its `id` via `params[:id]`

```ruby
@vendor = @vendor_service.fetch_by_id(params[:vendor_id])
@vendor.id = params[:id]
```

Would you want to use the same ID in both cases (`params[:vendor_id]`)? 

That being said, once you fetch the object you dont need to assign its ID - it should already be set by the fetching process which inflates that record with the ID already set.

**Comment by ThatsNinja** [comment] 2016-02-22 19:50
Thanks for getting back with me on this @ruckus. I'm still seeing the same error.

`:vendor_id` and `:id` are synonymous in my params. As mentioned, the controller code above is the result of me relentlessly stripping down and re-factoring over the course of many hours. Please, forgive me :smile:

Reading the trace, above, it looks like `quickbooks-ruby`'s call to `roxml` is what's invoking ActiveSupport.

I'm sure I'm doing something wrong, but I can't see it. What other information could I provide?

**Comment by ruckus** [comment] 2016-02-23 03:54
Well the real question is why is ActiveSupport/StrongParameters throwing that exception. I checked out the strong_parameters source for that method at:

https://github.com/rails/rails/blob/4-2-stable/actionpack%2Flib%2Faction_controller%2Fmetal%2Fstrong_parameters.rb#L251

So for some reason its being expected and not present / available.

It would be nice to by-pass strong parameters and remove it from the equation. What about taking your `params` hash and getting a raw Ruby Hash and then using that in your assignments - your current `params` is an instance of strong_parameters so it might be bringing too much baggage to the table. 

Try something like this:

```ruby
def update
  data = HashWithIndifferentAccess.new(params.to_hash)
  @vendor = @vendor_service.fetch_by_id(data[:vendor_id])
  #... rest of your lines but using +data+ instead of +params+
end
```

Separately, I see that you're assigning a raw string to `vendor.billing_address` which is invalid. You will need to instantiate a `Quickbooks::Model::PhysicalAddress` object and assign it to the `vendor.billing_address` property.

**Comment by ThatsNinja** [comment] 2016-02-23 14:45
Brilliant, @ruckus! That's done it. I've got a half hour of cleanup to do, and then I'll paste my working controller code.

**Comment by minimul** [comment] 2016-03-31 09:42
@ThatsNinja Can you paste in the working controller code?

**Comment by ThatsNinja** [comment] 2016-03-31 12:36
Wow, this one hit the floor. Thanks for the nudge, @minimul!

```
def update
    @vendor = @vendor_service.fetch_by_id params[:vendor_id]
    data = HashWithIndifferentAccess.new params.to_hash

    @vendor.given_name = data[:given_name]
    @vendor.family_name = data[:family_name]
    @vendor.display_name = data[:display_name]
    @vendor.company_name = data[:company_name]
    @vendor.billing_address do |b|
      b.line1 = data[:billing_address][:line1]
    end
    @vendor.email_address = data[:primary_email_address][:address]
    @vendor.primary_phone do
      Quickbooks::Model::TelephoneNumber.new(data[:primary_phone])
    end
    @vendor.alternate_phone do
      Quickbooks::Model::TelephoneNumber.new(data[:alternate_phone])
    end
    @vendor.fax_phone do
      Quickbooks::Model::TelephoneNumber.new(data[:fax_phone])
    end
    @vendor.mobile_phone do
      Quickbooks::Model::TelephoneNumber.new(data[:mobile_phone])
    end

    respond_to do |format|
      if @vendor_service.update(@vendor)
        format.html do
          redirect_to(
            '/vendors',
            notice: 'Vendor was successfully updated.'
          )
        end
        format.json { render 'vendors#index', status: :ok }
      else
        format.html { render :edit }
        format.json do
          render json: @vendor.errors, status: :unprocessable_entity
        end
      end
    end
  end
```
Here's my working controller code. Thanks again to @ruckus.

**Comment by ruckus** [comment] 2016-03-31 15:33
Thanks everyone. It looks like the takeaway is one cannot just pass in `params` from a controller straight into any `quickbooks-ruby` model objects, or at least "sanitize" it first by scrubbing it:

`data = HashWithIndifferentAccess.new(params.to_hash)`

Safe to say we can close this?

**Comment by ThatsNinja** [comment] 2016-03-31 15:46
That's certainly my take-away. I would consider this issue closed. Thanks again, @ruckus and @minimul!

**Closed** 2016-03-31 15:46 UTC
